/** @type {import('tailwindcss').Config} */
// Ported verbatim from the Stitch design system (project 14936290080923989280)
// so the exported markup can be used with minimal translation. See
// stitch_source/*.html for the original exports this was extracted from.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#003420",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#49617f",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#b0c8eb",
        "secondary-container": "#c4dcff",
        "tertiary-fixed-dim": "#62dca4",
        "on-tertiary-fixed": "#002113",
        surface: "#f7f9fc",
        "surface-container-high": "#e6e8eb",
        "surface-dim": "#d8dadd",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "primary-fixed-dim": "#a5c8ff",
        tertiary: "#006c48",
        "tertiary-container": "#1fa874",
        "on-secondary-fixed-variant": "#314865",
        "primary-container": "#3395ff",
        "inverse-on-surface": "#eff1f4",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#002d58",
        error: "#ba1a1a",
        "on-surface-variant": "#404753",
        "on-tertiary-fixed-variant": "#005235",
        "on-secondary-fixed": "#001c37",
        "on-primary-fixed-variant": "#004785",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        primary: "#005faf",
        "on-background": "#191c1e",
        outline: "#717784",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "inverse-primary": "#a5c8ff",
        "outline-variant": "#c0c7d5",
        background: "#f7f9fc",
        secondary: "#49607e",
        "surface-bright": "#f7f9fc",
        "tertiary-fixed": "#7ff9be",
        "on-primary-fixed": "#001c3a",
        "secondary-fixed": "#d2e4ff",
        "surface-container-highest": "#e0e3e6",
        "surface-tint": "#005faf",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "14px",
        lg: "20px",
        xs: "4px",
        gutter: "16px",
        xl: "28px",
        "margin-mobile": "16px",
        sm: "8px",
        "margin-desktop": "32px",
        base: "4px",
      },
      fontFamily: {
        // Swapped from Inter (flagged as an overused "safe" default) to Plus Jakarta
        // Sans — a warmer, more distinctive geometric sans still built for dense UI.
        "label-md": ["'Plus Jakarta Sans'"],
        "headline-md": ["'Plus Jakarta Sans'"],
        "headline-sm": ["'Plus Jakarta Sans'"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'"],
        "body-lg": ["'Plus Jakarta Sans'"],
        "label-sm": ["'Plus Jakarta Sans'"],
        "headline-lg": ["'Plus Jakarta Sans'"],
        "body-md": ["'Plus Jakarta Sans'"],
      },
      fontSize: {
        // Tightened from the original Stitch export — the 32px page titles and 24px
        // spacing unit read as oversized/"zoomed" for a dense ops dashboard.
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["18px", { lineHeight: "25px", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "27px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "31px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["13.5px", { lineHeight: "19px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
